apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: arch-function-3b
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=arch-function-3b
        - --model_id=katanemo/Arch-Function-3B
      resources:
        limits:
          memory: 10Gi
          nvidia.com/gpu: "1"
        requests:
          memory: 10Gi
          nvidia.com/gpu: "1"