apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen2-5-coder-1-5b
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=qwen2-5-coder-1-5b
        - --model_id=Qwen/Qwen2.5-Coder-1.5B-Instruct
      resources:
        limits:
          memory: 10Gi
          nvidia.com/gpu: "1"
        requests:
          memory: 10Gi
          nvidia.com/gpu: "1"