apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: uigen-x-4b
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=uigen-x-4b
        - --model_id=Tesslate/UIGEN-X-4B-0729
      resources:
        limits:
          memory: 10Gi
          nvidia.com/gpu: "1"
        requests:
          memory: 10Gi
          nvidia.com/gpu: "1"